import Head from 'next/head'
import Homelayuot from "../components/homelayout";
import Hero from "../components/Hero/hero";
import Advan from "../components/advan/advan"

export default function Home() {
    return (
        <div>
            <Head>
                <title>PORTER</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Homelayuot>
               <Hero/>
                <Advan/>
            </Homelayuot>

        </div>
    )
}
